sudo: required
dist: trusty
language: node_js

cache:
  directories:
    - node_modules
    - ~/.selenium-assistant

node_js:
  - 'stable'

# Read more here: https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\""
  - sleep 3 # give xvfb some time to start
install:
  - npm install

# Jobs split up the Travis tasks into multiple sections
jobs:
  include:
    - stage: "Test Packages"
      - script: gulp test --package="workbox-core"
      - script: gulp test --package="TEST"
    - stage: "Run pr-bot"
      before_script: skip
      script: npm run bot
