language: node_js

sudo: required

os:
  - osx

cache:
  directories:
    - ~/.selenium-assistant

node_js:
  - 8

install:
  - npm ci

before_script:
  - "sudo /usr/bin/safaridriver --enable"
  - "sudo defaults write com.apple.Safari AllowRemoteAutomation 1"

script:
  - gulp test

after_success:
  - npm run coveralls
  - npm run bot
